### ISSUE TITLE
ui-bootstrap-tpls problem

### ISSUE THREAD

**Issue by idoo** [hung-phan/generator-rails-angular-require#2]
ActionController::RoutingError (No route matches [GET] "/assets/ui-bootstrap-tpls.js"):

**Comment by hung-phan** [comment]
It causes by digest config in development with `require.js gem`. @idoo, You can turn off to make it work.

`config/environments/development.rb`

```
  # Asset digests allow you to set far-future HTTP expiration dates on all assets,
  # yet still be able to expire them through the digest params.
  config.assets.digest = false
```

**Comment by hung-phan** [comment]
This problem happens with `requirejs-rails` gem. I think they will have a fix in the future.
